export class LanguageConfig {
    public en: any;
    public es: any;

    constructor() {
        this.en = {
            common: {
                welcomeToApp: 'Welcome to Crypto ICO!',
                chooseTfaOption: 'Chose a two-factor authentication option',
                atLeast: 'at least',
                characters: 'characters',
                accountType: 'Account type',
                register: 'Register',
                forgotPassword: 'Forgot your password?',
                facebookLogin: 'Login with Facebook',
                gmailLogin: 'Login with Gmail',
                token: 'Token',
                continue: 'Continue',
                login: 'Login',
                logout: 'Logout',
                signup: 'Sign up',
                disable: 'Disable',
                enable: 'Enable',
                loginSecurity: 'Login security',
                others: 'Others',
                acceptTerms: 'I agree to Crypto ICO terms',
                registerStarted: 'Started with Crypto ICO!',
                createAccount: 'Create your account',
                passwordRequest: 'New password request',
                tokenEmailSent: 'A new token has been sent to your email',
                successConfirm: 'Confirmed successfully',
                success: 'Success',
                newToken: 'New token request',
                changePassword: 'Change your password',
                passwordChanged: 'Password changed',
                save: 'Save',
                user: 'User',
                proof: 'Proof of address',
                checkIt: 'Check it',
                documentsReview: 'Documents review',
                decline: 'Decline',
                adminCreated: 'Admin created',
                createAdmin: 'Create new admin account',
                create: 'Create',
                unrecognizedDevice: 'Unrecognized device',
                deviceConfirmed: 'Device confirmed',
                tfaTokenVerification: 'Login access token',
                provideToken: 'Please provide the token sent to your email to complete the verification',
                adminPanel: 'Admin panel',
            },
            menu: {
                introduction: 'Introduction',
                home: 'Home',
                buy: 'Buy',
                profile: 'Profile',
                settings: 'Settings',
                createAdmin: 'Create administrator',
                confirmUsers: 'Confirm users',
            },
            inputs: {
                email: 'Email address',
                password: 'Password',
                passwordConfirm: 'Password confirm',
                captchaConfirm: 'Captcha confirm',
                country: 'Country',
                state: 'State',
                town: 'Town',
                postalCode: 'Postal code',
                suburb: 'Suburb',
                street: 'Street',
                numExt: 'Num ext',
                address: 'Address',
                gender: 'Gender',
                name: 'Name',
                birthdate: 'Birthdate',
                domicile: 'Search domicile',
                phone: 'Phone',
                idfront: 'Identification (Front face)',
                idback: 'Identification (Back face)',
                proof: 'Proof of address',
                errors: {
                    required: 'Required field',
                    format: 'Invalid format',
                    length: 'Length must be',
                    passwordMatch: 'Passwords must match',
                    isMajor: 'You need to be of legal age',
                    domicile: 'Enter a valid domicile'
                }
            },
            tfa: {
                sendToken: 'Send a verification token to email',
                title: 'Two Factor Authentication',
                subtitle: 'Enable or disable a two-factor authentication option',
                // tslint:disable-next-line: max-line-length
                descritpion: 'Add additional security with two-step authentication. You can active one or more options to authenticate in two steps.',
                step1: 'Provide your email and password',
                step2: 'Provide a token code, configured by an external application using a QR code or by email.',
                emailDescription: 'To access with this option, the next time you try to log in, you will be able to get a token by email.',
                emailStrongDescription: 'This option always will be available if you active any other.',
                // tslint:disable-next-line: max-line-length
                googleDescription: 'To get a token code, download from your mobile app store Google Authenticator and scan the following QR code.',
            },
            backend: {
                errors: {
                    399: 'Something wrong',
                    452: 'Invalid email or password',
                    453: 'Invalid account type for login',
                    454: 'Invalid TFA token',
                    455: 'Invalid OAuth token',
                    456: 'This email has already been taken',
                    457: 'User not found',
                    458: 'Invalid token',
                    459: 'The token has been expired',
                    460: 'We can not recognize this device.'
                }
            },
            errors: {
                declineDocuments: 'Verification of documents without success',
                declineDocumentsList: 'The following documents could not be verified: '
            }
        };
        this.es = {
            common: {
                welcomeToApp: '¡Bienvenido a Crypto ICO!',
                chooseTfaOption: 'Selecciona opción para la autenticación en dos pasos',
                atLeast: 'al menos',
                characters: 'carácteres',
                accountType: 'Tipo de cuenta',
                register: 'Registrarse',
                forgotPassword: 'Recuperar contraseña',
                facebookLogin: 'Iniciar con Facebook',
                gmailLogin: 'Iniciar con Gmail',
                token: 'Código',
                continue: 'Continuar',
                login: 'Iniciar sesión',
                logout: 'Cerrar sesión',
                signup: 'Regístrate',
                disable: 'Habilitar',
                enable: 'Deshabilitar',
                loginSecurity: 'Seguridad de inicio de sesión',
                others: 'Otros',
                acceptTerms: 'Estoy de acuerdo con los términos de Crypto ICO',
                registerStarted: 'Únete a Crypto ICO',
                createAccount: 'Crea tu cuenta',
                passwordRequest: 'Solicitar nueva contraseña',
                tokenEmailSent: 'Un nuevo código de verificación ha sido enviado a tu correo',
                successConfirm: 'Confirmado correctamente',
                success: 'Éxito',
                newToken: 'Obtener nuevo código de verificación',
                changePassword: 'Cambiar contraseña',
                passwordChanged: 'Contraseña restablecida',
                save: 'Guardar',
                user: 'Usuario',
                proof: 'Comprobante de domicilio',
                checkIt: 'Revizar',
                documentsReview: 'Revisión de documentos',
                decline: 'Rechazar',
                adminCreated: 'Administrador creado',
                createAdmin: 'Crear cuenta de administrador',
                create: 'Crear',
                unrecognizedDevice: 'Dispositivo no reconocido',
                deviceConfirmed: 'Dispositivo confirmado',
                tfaTokenVerification: 'Verficacion de codígo para inicio de sesión',
                provideToken: 'Por favor ingresa el codigo enviado a tu correo para completar la verificación',
                adminPanel: 'Panel de administrador',
            },
            menu: {
                introduction: 'Acerca de Crypto ICO',
                home: 'Inicio',
                buy: 'Comprar',
                profile: 'Perfil',
                settings: 'Configuraciones',
                createAdmin: 'Crear administrador',
                confirmUsers: 'Confirmar usuarios',
            },
            inputs: {
                email: 'Correo',
                password: 'Contraseña',
                passwordConfirm: 'Confirma la contraseña',
                captchaConfirm: 'Realiza el captcha',
                country: 'País',
                state: 'Estado',
                town: 'Ciudad',
                postalCode: 'Código postal',
                suburb: 'Colonia',
                street: 'Calle',
                numExt: 'Num ext',
                address: 'Domicilio',
                gender: 'Género',
                name: 'Nombre',
                birthdate: 'Fecha de nacimiento',
                domicile: 'Buscar domicilio',
                phone: 'Telefono',
                idfront: 'Identificación (Cara frontal)',
                idback: 'Identificación (Cara del reverso)',
                proof: 'Comprobante de domicilio',
                errors: {
                    required: 'Campo requerido',
                    format: 'Formato invalido',
                    length: 'La longitud debe de ser',
                    passwordMatch: 'Las contraseñas deben coincidir',
                    isMajor: 'Necesitas ser mayor de edad',
                    domicile: 'Introduce un domicilio valido'
                }
            },
            tfa: {
                sendToken: 'Enviar código de verificación al correo',
                title: 'Autenticación en dos pasos',
                subtitle: 'Habilite o deshabilite una opción de autenticación en dos pasos',
                // tslint:disable-next-line: max-line-length
                descritpion: 'Agregue seguridad adicional con la autenticación de dos pasos. Puede activar una o más opciones para autenticarse en dos pasos.',
                step1: 'Proporciona tu correo y contraseña.',
                // tslint:disable-next-line: max-line-length
                step2: 'Proporcione un código de verificación, configurado por una aplicación externa utilizando un código QR o por correo electrónico.',
                // tslint:disable-next-line: max-line-length
                emailDescription: 'Para acceder con esta opción, la próxima vez que intente iniciar sesión, podrá obtener un código de verificación por correo electrónico.',
                emailStrongDescription: 'Esta opción siempre estará disponible si activa cualquier otra.',
                // tslint:disable-next-line: max-line-length
                googleDescription: 'Para obtener un código de verificación, descargue desde su tienda de aplicaciones móviles Google Authenticator y escanee el siguiente código QR.',
            },
            backend: {
                errors: {
                    399: 'Algo salió mal',
                    452: 'Correo o contraseña invalido',
                    453: 'Tipo de cuenta invalido para iniciar',
                    454: 'Código TFA invalido',
                    455: 'Código OAuth invalido',
                    456: 'Este correo ya está en uso',
                    457: 'Usuario no encontrado',
                    458: 'Código de verificación invalido',
                    459: 'El código de verificación ha expirado',
                    460: 'No podemos reconocer este dispositivo'
                }
            },
            errors: {
                declineDocuments: 'Verificación de documentos sin éxito',
                declineDocumentsList: 'Los siguientes documentos no pudieron ser verificados: '
            }
        };
    }
}
